- name: Prepare /etc/hosts file
  lineinfile:
    dest: /etc/hosts
    line: "{{ item }}"
  with_items:
    - "{{ master_fqdn }} {{ master_ip }}"
    - "{{ worker_1_fqdn }} {{ worker_1_ip }}"
    - "{{ worker_2_fqdn }} {{ worker_2_ip }}"

- name: install APT Transport HTTPS
  apt:
    name: apt-transport-https
    state: present

- name: add docker apt-key
  apt_key: 
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: add docker apt repo
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
    state: present
    filename: 'docker'

- name: install Docker
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: true
  vars:
    packages:
    - docker-ce
    - docker-ce-cli
    - containerd.io
  notify:
    - docker status  

- name: add Kubernetes apt-key
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present

- name: add Kubernetes APT repository
  apt_repository:
    repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
    state: present
    filename: 'kubernetes'

- name: install kubelet
  apt:
    name: kubelet={{ kubelet_ver }}
    state: present
    update_cache: true

- name: install kubeadm
  apt:
    name: kubeadm={{ kubeadm_ver }}
    state: present

- name: Remove swapfile from /etc/fstab
  mount:
    name: "{{ item }}"
    fstype: swap
    state: absent
  with_items:
    - swap
    - none

- name: Disable swap
  command: swapoff -a
  when: ansible_swaptotal_mb > 0


- name: ip forwardin
  shell: echo "1" > /proc/sys/net/ipv4/ip_forward

- name: enable modprobe br_netfilter
  modprobe:
    name: br_netfilter
    state: present
