- hosts: master
  become: yes
  tasks:

    - name: collect facts about system services
      service_facts:
      register: services_state

    - name: initialize the cluster
      shell: kubeadm init --pod-network-cidr={{ pod_network_cidr }} >> cluster_initialized.txt
      args:
        chdir: $HOME
        creates: cluster_initialized.txt
      become: yes
      become_user: root

    - name: create .kube directory
      become: yes
      become_user: deploy
      file:
        path: $HOME/.kube
        state: directory
        mode: 0755

    - name: copy admin.conf to user's kube config
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/deploy/.kube/config
        remote_src: yes
        owner: deploy

    # - name: install etcd
    #   become: yes
    #   become_user: deploy
    #   shell: kubectl apply -f https://docs.projectcalico.org/v3.5/getting-started/kubernetes/installation/hosted/etcd.yaml >> etcd_setup.txt
    #   args:
    #     chdir: $HOME
    #     creates: etcd_setup.txt
    - name: install Pod network
      become: yes
      become_user: deploy
      shell: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/2140ac876ef134e0ed5af15c65e414cf26827915/Documentation/kube-flannel.yml >> pod_network_setup.txt
      args:  
        chdir: $HOME
        creates: pod_network_setup.txt

# kubectl apply -f https://docs.projectcalico.org/v3.5/getting-started/kubernetes/installation/hosted/etcd.yaml
# kubectl apply -f https://docs.projectcalico.org/v3.5/getting-started/kubernetes/installation/hosted/calico.yaml
#"{{ role_path }}/files/calico.yaml"
#kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/a70459be0084506e4ec919aa1c114638878db11b/Documentation/kube-flannel.yml >> pod_network_setup.txt

# https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml